language: nix

cache:
  directories:
  - $HOME/nix.store

before_install:
  - sudo mkdir -p /etc/nix 
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store https://hydra.iohk.io" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs=" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

script: 
   - nix build -L --cores 0 -f default.nix pretty-types.checks
